strona_Authors
infoshareacademy/jfdz12-fantasy-code pull request #15
Opened 2019-09-13 19:19 UTC by mikolaj-sar

Hej, Strona "authors" zrobiona w odrębnym pliku html. Do pliku main.css wkleiłem elementy kodu do strony.

2019-09-14 10:28 UTC, krichert requested changes

2019-09-14 10:28 UTC, krichert commented on authors.html
> +            <img class="Maxymilian-image" src="Ikony/niebieski proporczyk.png">
use english, please do not make spaces in file names

2019-09-14 10:28 UTC, krichert commented on main.css
> +    height: 87%;
why 87%? it is not common value

2019-09-14 10:28 UTC, krichert commented on main.css
> +    font-family: ‘LABRIT’;
use font-family if the  first one will not load ->  e.g. `font-family: ‘LABRIT’, sans-serif;`

2019-09-15 17:37 UTC, Tarnoruda commented
This is older version, rejecting.

2019-09-15 17:37 UTC, closed without merging