Fz12 fc 1
infoshareacademy/jfdz12-fantasy-code pull request #30
Opened 2019-11-14 04:15 UTC by Tarnoruda

nowa strona + zaimplementowana gra

2019-11-15 21:04 UTC, piotr-andrzej-bochenek approved these changes
Approved, but renderLife function is in it's old version (wrongly injecting innerHTML and appending children), it's much improved in PullRequest #29, awaiting for a review.

2019-11-15 22:00 UTC, krichert requested changes

2019-11-15 22:00 UTC, krichert commented on game/.vscode/settings.json
> +    "liveServer.settings.port": 5501
we do not need this in repository

2019-11-15 22:00 UTC, krichert commented on game/game.css
> +    /* position: relative; */
left comment

2019-11-15 22:00 UTC, krichert commented on game/game.css
> +.map_wall--image{
once it is map_wall then map--floor, change it to map-wall and map-floor for example

2019-11-15 22:00 UTC, krichert commented on main.js
> +const cookies = document.querySelector(".cookies");
do we have a task in sprint about cookies?

2019-11-15 22:40 UTC, piotr-andrzej-bochenek commented on game/game.css
> +.map_wall--image{
changed to map--wall

2019-11-15 22:45 UTC, piotr-andrzej-bochenek commented on main.js
> +const cookies = document.querySelector(".cookies");
we don't have

2019-11-16 14:11 UTC, karol-nogal approved these changes

2019-11-17 11:48 UTC, Tarnoruda commented
looks like done

2019-11-17 11:49 UTC, karol-nogal approved these changes

2019-11-17 11:50 UTC, Tarnoruda reviewed
28 / 122 re-viewed

2019-11-17 12:24 UTC, krichert approved these changes
Tylko ze względu na prezentację daje approve :)

2019-11-17 12:56 UTC, merged